[package]
name = "save-server"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
base64.workspace = true
aws-sdk-s3.workspace = true
anyhow.workspace = true
axum.workspace = true
ciborium.workspace = true
hex.workspace = true
save-crypto = { path = "../save-crypto" }
save-domain = { path = "../save-domain" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[[bin]]
name = "mh-save-server"
path = "src/main.rs"

[dev-dependencies]
ed25519-dalek.workspace = true
