#!/usr/bin/env python3
"""Deterministic black-box exercise for the PostgreSQL + S3 service backend."""

from __future__ import annotations

import argparse
import atexit
import base64
import hashlib
import json
import os
import subprocess
import tempfile
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any


# This fixture is generated by `mh-save crypto-device-fixture`: the public
# certificate is committed, and its deterministic Ed25519 test signing seed is
# deliberately fixed at 0x24. It is only used against the disposable Compose
# stack. Keeping the signer here makes this black-box E2E exercise the same
# challenge/signature middleware used by production clients.
FIXTURE_DEVICE_SIGNING_SEED = bytes([0x24]) * 32
ED25519_PKCS8_PREFIX = bytes.fromhex("302e020100300506032b657004220420")


def canonical_http_request(
    method: str,
    path_and_query: str,
    body: bytes,
    challenge_id: str,
    nonce_b64: str,
    timestamp: int,
) -> bytes:
    fields = (
        "mh-save-sync/http-auth/v1",
        method.upper(),
        path_and_query,
        hashlib.sha256(body).hexdigest(),
        challenge_id,
        nonce_b64,
        str(timestamp),
    )
    return b"".join(
        len(field.encode("utf-8")).to_bytes(4, "big") + field.encode("utf-8")
        for field in fields
    )


class FixtureSigner:
    def __init__(self) -> None:
        descriptor, raw_path = tempfile.mkstemp(prefix="mh-save-compose-e2e-ed25519-", suffix=".pem")
        self.path = Path(raw_path)
        try:
            os.fchmod(descriptor, 0o600)
            pem = base64.b64encode(ED25519_PKCS8_PREFIX + FIXTURE_DEVICE_SIGNING_SEED).decode()
            with os.fdopen(descriptor, "wb") as key_file:
                key_file.write(
                    "\n".join(
                        ("-----BEGIN PRIVATE KEY-----", pem, "-----END PRIVATE KEY-----", "")
                    ).encode()
                )
        except BaseException:
            try:
                os.close(descriptor)
            except OSError:
                pass
            self.close()
            raise
        atexit.register(self.close)

    def sign(self, message: bytes) -> bytes:
        descriptor, raw_message_path = tempfile.mkstemp(prefix="mh-save-compose-e2e-message-")
        message_path = Path(raw_message_path)
        try:
            with os.fdopen(descriptor, "wb") as message_file:
                message_file.write(message)
            result = subprocess.run(
                [
                    "openssl",
                    "pkeyutl",
                    "-sign",
                    "-rawin",
                    "-inkey",
                    str(self.path),
                    "-in",
                    str(message_path),
                ],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
        finally:
            message_path.unlink(missing_ok=True)
        if result.returncode != 0 or len(result.stdout) != 64:
            raise RuntimeError(
                "OpenSSL Ed25519 fixture signing failed: "
                + result.stderr.decode(errors="replace").strip()
            )
        return result.stdout

    def public_key_b64(self) -> str:
        result = subprocess.run(
            ["openssl", "pkey", "-pubout", "-outform", "DER", "-in", str(self.path)],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )
        if result.returncode != 0 or len(result.stdout) < 32:
            raise RuntimeError(
                "OpenSSL Ed25519 fixture public-key extraction failed: "
                + result.stderr.decode(errors="replace").strip()
            )
        return base64.b64encode(result.stdout[-32:]).decode()

    def close(self) -> None:
        self.path.unlink(missing_ok=True)


def object_id(label: str) -> str:
    return hashlib.sha256(label.encode()).hexdigest()


def encoded(payload: bytes) -> tuple[str, str]:
    return (
        hashlib.sha256(payload).hexdigest(),
        base64.b64encode(payload).decode(),
    )


def public_identity_fixture() -> dict[str, str]:
    repo = Path(__file__).resolve().parent.parent
    return json.loads(
        (repo / "tests/fixtures/device-identity-public.json").read_text()
    )


class Api:
    def __init__(self, base_url: str) -> None:
        self.base_url = base_url.rstrip("/")
        self.account: str | None = None
        self.device: str | None = None
        self.signer = FixtureSigner()

    def authenticate_as_fixture(self) -> None:
        identity = public_identity_fixture()
        if self.signer.public_key_b64() != identity["device_public_key_b64"]:
            raise RuntimeError("fixture Ed25519 private key does not match device certificate")
        self.account = identity["account_handle"]
        self.device = identity["cert_id"]

    @staticmethod
    def requires_resource_auth(method: str, path: str) -> bool:
        return (
            method == "POST"
            and (
                path == "/v1/snapshots/begin"
                or (
                    path.startswith("/v1/snapshots/")
                    and path.endswith(("/chunks", "/manifest", "/commit"))
                )
                or (path.startswith("/v1/devices/") and path.endswith("/revoke"))
                or (path.startswith("/v1/conflicts/") and path.endswith("/resolve"))
            )
        ) or (
            method == "GET"
            and (
                path.startswith(("/v1/heads/", "/v1/history/", "/v1/conflicts/"))
                or (
                    path.startswith("/v1/snapshots/")
                    and path.endswith("/encrypted-bundle")
                )
            )
        )

    def signed_headers(self, method: str, path: str, body: bytes) -> dict[str, str]:
        if self.account is None or self.device is None:
            raise RuntimeError(f"authenticated request has no fixture identity: {method} {path}")
        challenge = self.request(
            "POST",
            "/v1/accounts/challenge",
            {"account_handle": self.account, "device_cert_id": self.device},
        )
        timestamp = int(time.time())
        signature = self.signer.sign(
            canonical_http_request(
                method,
                path,
                body,
                challenge["challenge_id"],
                challenge["nonce_b64"],
                timestamp,
            )
        )
        return {
            "x-mh-account": self.account,
            "x-mh-device-cert": self.device,
            "x-mh-challenge-id": challenge["challenge_id"],
            "x-mh-nonce": challenge["nonce_b64"],
            "x-mh-timestamp": str(timestamp),
            "x-mh-signature": base64.b64encode(signature).decode(),
        }

    def request(
        self,
        method: str,
        path: str,
        payload: dict[str, Any] | None = None,
        expected: tuple[int, ...] = (200,),
    ) -> Any:
        data = None
        headers: dict[str, str] = {}
        if payload is not None:
            data = json.dumps(payload, separators=(",", ":")).encode()
            headers["content-type"] = "application/json"
        if self.requires_resource_auth(method, path):
            headers.update(self.signed_headers(method, path, data or b""))
        request = urllib.request.Request(
            self.base_url + path,
            data=data,
            headers=headers,
            method=method,
        )
        try:
            with urllib.request.urlopen(request, timeout=15) as response:
                body = response.read()
                status = response.status
        except urllib.error.HTTPError as error:
            body = error.read()
            status = error.code
        if status not in expected:
            raise RuntimeError(
                f"{method} {path}: expected {expected}, got {status}: "
                f"{body.decode(errors='replace')}"
            )
        if not body:
            return None
        try:
            return json.loads(body)
        except json.JSONDecodeError:
            return body.decode(errors="replace")


def put_object(
    api: Api,
    upload_id: str,
    kind: str,
    identifier: str,
    payload: bytes,
) -> None:
    digest, body = encoded(payload)
    suffix = "chunks" if kind == "chunk" else "manifest"
    key = "chunk_id" if kind == "chunk" else "manifest_id"
    api.request(
        "POST",
        f"/v1/snapshots/{upload_id}/{suffix}",
        {key: identifier, "sha256": digest, "bytes_b64": body},
        (204,),
    )


def begin(
    api: Api,
    account: str,
    device: str,
    logical_save: str,
    manifest: str,
    chunks: list[str],
    base: str | None,
    parents: list[str],
) -> dict[str, Any]:
    return api.request(
        "POST",
        "/v1/snapshots/begin",
        {
            "account_handle": account,
            "device_cert_id": device,
            "logical_save_id": logical_save,
            "base_head": base,
            "parents": parents,
            "encrypted_manifest_id": manifest,
            "chunk_ids": chunks,
        },
    )


def commit(api: Api, upload: str, snapshot: str) -> dict[str, Any]:
    return api.request(
        "POST",
        f"/v1/snapshots/{upload}/commit",
        {"snapshot_id": snapshot},
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--base-url", default="http://127.0.0.1:18080")
    args = parser.parse_args()
    api = Api(args.base_url)

    ready = api.request("GET", "/ready")
    if ready["backend"] != "postgres-s3":
        raise RuntimeError(f"persistent backend required, got {ready}")

    identity = public_identity_fixture()
    account = identity["account_handle"]
    device = identity["cert_id"]
    api.request(
        "POST",
        "/v1/accounts/bootstrap",
        {
            "account_handle": account,
            "root_public_key_b64": identity["root_public_key_b64"],
        },
        (201,),
    )
    api.request(
        "POST",
        "/v1/accounts/bootstrap",
        {
            "account_handle": account,
            "root_public_key_b64": base64.b64encode(bytes(32)).decode(),
        },
        (409,),
    )
    api.request(
        "POST",
        "/v1/devices/register",
        {
            "account_handle": account,
            "cert_id": device,
            "device_public_key_b64": identity["device_public_key_b64"],
            "certificate_b64": base64.b64encode(b"invalid-certificate").decode(),
        },
        (400,),
    )
    api.request(
        "POST",
        "/v1/devices/register",
        {
            "account_handle": account,
            "cert_id": device,
            "device_public_key_b64": identity["device_public_key_b64"],
            "certificate_b64": identity["certificate_b64"],
        },
        (201,),
    )
    api.authenticate_as_fixture()

    run = str(time.time_ns())
    logical_save = f"e2e-{run}"
    chunk1, chunk2, chunk3 = (
        object_id(f"{run}:chunk:{index}") for index in range(1, 4)
    )
    manifest1, manifest2, manifest3 = (
        object_id(f"{run}:manifest:{index}") for index in range(1, 4)
    )
    snapshot1, snapshot2, snapshot3 = (
        object_id(f"{run}:snapshot:{index}") for index in range(1, 4)
    )

    first = begin(
        api, account, device, logical_save, manifest1, [chunk1], None, []
    )
    if first["missing_chunk_ids"] != [chunk1]:
        raise RuntimeError(f"unexpected first missing set: {first}")
    put_object(api, first["upload_id"], "chunk", chunk1, b"encrypted-chunk-one")
    put_object(
        api, first["upload_id"], "manifest", manifest1, b"encrypted-manifest-one"
    )
    first_commit = commit(api, first["upload_id"], snapshot1)
    if first_commit["outcome"] != "first-snapshot":
        raise RuntimeError(f"unexpected first commit: {first_commit}")

    branch_a = begin(
        api,
        account,
        device,
        logical_save,
        manifest2,
        [chunk1, chunk2],
        snapshot1,
        [snapshot1],
    )
    if branch_a["missing_chunk_ids"] != [chunk2]:
        raise RuntimeError(f"dedupe/missing-set failed: {branch_a}")
    branch_b = begin(
        api,
        account,
        device,
        logical_save,
        manifest3,
        [chunk3],
        snapshot1,
        [snapshot1],
    )
    put_object(api, branch_a["upload_id"], "chunk", chunk2, b"encrypted-chunk-two")
    put_object(
        api,
        branch_a["upload_id"],
        "manifest",
        manifest2,
        b"encrypted-manifest-two",
    )
    fast_forward = commit(api, branch_a["upload_id"], snapshot2)
    if fast_forward["outcome"] != "fast-forward":
        raise RuntimeError(f"expected fast-forward: {fast_forward}")

    put_object(
        api, branch_b["upload_id"], "chunk", chunk3, b"encrypted-chunk-three"
    )
    put_object(
        api,
        branch_b["upload_id"],
        "manifest",
        manifest3,
        b"encrypted-manifest-three",
    )
    conflict = commit(api, branch_b["upload_id"], snapshot3)
    if (
        conflict["outcome"] != "conflict"
        or conflict["head"] != snapshot2
        or conflict["conflict_snapshot"] != snapshot3
    ):
        raise RuntimeError(f"conflict CAS failed: {conflict}")

    head = api.request("GET", f"/v1/heads/{logical_save}")
    history = api.request("GET", f"/v1/history/{logical_save}")
    conflicts = api.request("GET", f"/v1/conflicts/{logical_save}")
    if head != snapshot2 or len(history) != 3 or len(conflicts) != 1:
        raise RuntimeError(
            f"history invariant failed: head={head} "
            f"history={len(history)} conflicts={len(conflicts)}"
        )

    bad_chunk = object_id(f"{run}:bad")
    bad_manifest = object_id(f"{run}:bad-manifest")
    bad = begin(
        api,
        account,
        device,
        f"{logical_save}-bad-checksum",
        bad_manifest,
        [bad_chunk],
        None,
        [],
    )
    _, body = encoded(b"corrupt-at-transport")
    api.request(
        "POST",
        f"/v1/snapshots/{bad['upload_id']}/chunks",
        {"chunk_id": bad_chunk, "sha256": "00" * 32, "bytes_b64": body},
        (400,),
    )

    print(
        json.dumps(
            {
                "backend": ready["backend"],
                "logical_save_id": logical_save,
                "head": head,
                "history_count": len(history),
                "conflict_count": len(conflicts),
                "dedupe_missing_count": len(branch_a["missing_chunk_ids"]),
                "checksum_fail_closed": True,
                "certificate_fail_closed": True,
                "account_root_immutable": True,
            },
            indent=2,
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
