#!/usr/bin/env python3
"""Pin the 3usavetools MH3U transform offsets into the Rust converter crate."""

import hashlib
import runpy
import subprocess
import sys
from pathlib import Path


EXPECTED_SHA256 = "0753baafad37147cb4701b7315a9deb9055ff699f444d55fce537b4e1ae35deb"


def render(swaps: list[tuple[int, int]], monster: list[int], arena: list[int]) -> str:
    lines = [
        "// This file is generated by scripts/generate-mh3g-transform-table.py.",
        "// Source: https://github.com/fadillzzz/3usavetools, tag 0.3.1,",
        "// commit d20fea5d98d5c465841c8e5626dae6709622354a (MIT license).",
        f"// Source save_indices.py SHA-256: {EXPECTED_SHA256}",
        "",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
        "pub struct SwapSpan {",
        "    pub start: usize,",
        "    pub end: usize,",
        "}",
        "",
        f"pub const SWAP_SPANS: [SwapSpan; {len(swaps)}] = [",
    ]
    lines.extend(
        f"    SwapSpan {{ start: {start}, end: {end} }}," for start, end in swaps
    )
    lines.extend(
        [
            "];",
            "",
            f"pub const MONSTER_DISCOVERY_OFFSETS: [usize; {len(monster)}] = [",
        ]
    )
    lines.extend(f"    {offset}," for offset in monster)
    lines.extend(
        [
            "];",
            "",
            f"pub const ARENA_RECORD_OFFSETS: [usize; {len(arena)}] = [",
        ]
    )
    lines.extend(f"    {offset}," for offset in arena)
    lines.extend(["];", ""])
    return "\n".join(lines)


def main() -> None:
    if len(sys.argv) != 3:
        raise SystemExit("usage: generate-mh3g-transform-table.py INPUT OUTPUT")

    source, output = map(Path, sys.argv[1:3])
    if hashlib.sha256(source.read_bytes()).hexdigest() != EXPECTED_SHA256:
        raise SystemExit("unexpected 3usavetools save_indices.py hash")
    values = runpy.run_path(str(source))
    swaps = [tuple(map(int, span)) for span in values["saveFileSwap"]]
    monster = [int(offset) for offset in values["monsterDiscoveryState"]]
    arena = [int(offset) for offset in values["arenaRecord"]]
    if (len(swaps), len(monster), len(arena)) != (8509, 50, 62):
        raise SystemExit("unexpected transform-table counts")

    output.write_text(render(swaps, monster, arena), encoding="utf-8")
    subprocess.run(["rustfmt", "--edition", "2024", str(output)], check=True)


if __name__ == "__main__":
    main()
