#!/usr/bin/env python3
"""Extract the static MH3G user-body operations from the local MEOW v5 core."""

import hashlib
import marshal
import subprocess
import sys
from pathlib import Path


def render_array(name: str, values: tuple[int, ...]) -> list[str]:
    lines = [f"pub const {name}: [usize; {len(values)}] = ["]
    lines.extend(f"    {value}," for value in values)
    lines.extend(["];", ""])
    return lines


def main() -> None:
    if len(sys.argv) != 3:
        raise SystemExit("usage: generate-mh3g-meow-transform-table.py MEOW_CORE_PYC OUTPUT")

    source, output = map(Path, sys.argv[1:3])
    source_hash = hashlib.sha256(source.read_bytes()).hexdigest()
    namespace = {"__name__": "mh3u_transfer_core_v5_static_extract"}
    exec(marshal.loads(source.read_bytes()[16:]), namespace)

    arrays = [
        ("MEOW_USER_SWAP4", namespace["_USER_SWAP4"]),
        ("MEOW_USER_ARENA4", namespace["_USER_ARENA4"]),
        ("MEOW_USER_ID32", namespace["_USER_USER_ID32"]),
        ("MEOW_USER_SWAP2", namespace["_USER_SWAP2"]),
        ("MEOW_USER_CROWN", namespace["_USER_CROWN"]),
        ("MEOW_USER_MASKED_SWAP2", namespace["_USER_MASKED_SWAP2"]),
        ("MEOW_USER_MASKED_SWAP4", namespace["_USER_MASKED_SWAP4"]),
        ("MEOW_USER_OFFICIAL_FIX_SWAP2", namespace["_USER_OFFICIAL_FIX_SWAP2"]),
        ("MEOW_USER_OFFICIAL_FIX_SWAP4", namespace["_USER_OFFICIAL_FIX_SWAP4"]),
        ("MEOW_USER_OFFICIAL_FIX_ARENA4", namespace["_USER_OFFICIAL_FIX_ARENA4"]),
        ("MEOW_USER_OFFICIAL_FIX_COPY1", namespace["_USER_OFFICIAL_FIX_COPY1"]),
        ("MEOW_CARD_SWAP4", namespace["_CARD_SWAP4"]),
        ("MEOW_CARD_ARENA4", namespace["_CARD_ARENA4"]),
        ("MEOW_CARD_SWAP2", namespace["_CARD_SWAP2"]),
        ("MEOW_CARD_CROWN", namespace["_CARD_CROWN"]),
        ("MEOW_CARDBOX_SWAP4", namespace["_CARDBOX_SWAP4"]),
        ("MEOW_CARDBOX_ARENA4", namespace["_CARDBOX_ARENA4"]),
        ("MEOW_CARDBOX_SWAP2", namespace["_CARDBOX_SWAP2"]),
        ("MEOW_CARDBOX_CROWN", namespace["_CARDBOX_CROWN"]),
    ]
    lines = [
        "// This file is generated by scripts/generate-mh3g-meow-transform-table.py.",
        "// Static source: local MEOW v5 transfer core Python bytecode.",
        f"// Source SHA-256: {source_hash}",
        "",
    ]
    for name, values in arrays:
        lines.extend(render_array(name, tuple(map(int, values))))
    output.write_text("\n".join(lines), encoding="utf-8")
    subprocess.run(["rustfmt", "--edition", "2024", str(output)], check=True)


if __name__ == "__main__":
    main()
