using MHToolkit.MH3GSaveConverter.Windows.Models;

namespace MHToolkit.MH3GSaveConverter.Windows.Infrastructure;

/// <summary>
/// Runtime-selectable copy for the small native shell. English is the fallback
/// for all keys; switching the persisted preference updates every binding.
/// </summary>
public sealed class ConverterCopy : ObservableObject
{
    private AppLanguageOverride _language;

    public ConverterCopy(AppLanguageOverride language)
    {
        _language = language;
    }

    public void SetLanguage(AppLanguageOverride language)
    {
        if (_language == language)
        {
            return;
        }

        _language = language;
        OnAllPropertiesChanged();
    }

    public string AppTitle => Text(nameof(AppTitle));
    public string AppSubtitle => Text(nameof(AppSubtitle));
    public string Language => Text(nameof(Language));
    public string LanguageSystem => Text(nameof(LanguageSystem));
    public string LanguageChinese => Text(nameof(LanguageChinese));
    public string LanguageEnglish => Text(nameof(LanguageEnglish));
    public string AboutUpdates => Text(nameof(AboutUpdates));
    public string AboutDescription => Text(nameof(AboutDescription));
    public string CurrentVersion => Text(nameof(CurrentVersion));
    public string CheckForUpdates => Text(nameof(CheckForUpdates));
    public string CheckingForUpdates => Text(nameof(CheckingForUpdates));
    public string UpdateAvailableTitle => Text(nameof(UpdateAvailableTitle));
    public string UpdateAvailableSummary => Text(nameof(UpdateAvailableSummary));
    public string ReleaseNotes => Text(nameof(ReleaseNotes));
    public string NoReleaseNotes => Text(nameof(NoReleaseNotes));
    public string OpenReleasePage => Text(nameof(OpenReleasePage));
    public string UpToDateTitle => Text(nameof(UpToDateTitle));
    public string UpToDateMessage => Text(nameof(UpToDateMessage));
    public string UpdateCheckFailed => Text(nameof(UpdateCheckFailed));
    public string UpdateNetworkNote => Text(nameof(UpdateNetworkNote));
    public string Close => Text(nameof(Close));
    public string StageInput => Text(nameof(StageInput));
    public string StageInspect => Text(nameof(StageInspect));
    public string StageDryRun => Text(nameof(StageDryRun));
    public string StageWrite => Text(nameof(StageWrite));
    public string NextStep => Text(nameof(NextStep));
    public string NextAfterInspect => Text(nameof(NextAfterInspect));
    public string NextAfterDryRun => Text(nameof(NextAfterDryRun));
    public string NextAfterWrite => Text(nameof(NextAfterWrite));
    public string NextAfterCoreWriteWithOptionalData => Text(nameof(NextAfterCoreWriteWithOptionalData));
    public string NextAfterOptional => Text(nameof(NextAfterOptional));
    public string NextAfterRollback => Text(nameof(NextAfterRollback));
    public string GoToDryRun => Text(nameof(GoToDryRun));
    public string GoToCoreDryRun => Text(nameof(GoToCoreDryRun));
    public string ConfigureOptionalData => Text(nameof(ConfigureOptionalData));
    public string ContinueOptionalData => Text(nameof(ContinueOptionalData));
    public string ConfirmAndWrite => Text(nameof(ConfirmAndWrite));
    public string ReturnToCoreFlow => Text(nameof(ReturnToCoreFlow));
    public string ReviewTransaction => Text(nameof(ReviewTransaction));
    public string HeroTitle => Text(nameof(HeroTitle));
    public string HeroDescription => Text(nameof(HeroDescription));
    public string HeroSafety => Text(nameof(HeroSafety));
    public string ArtworkSource => Text(nameof(ArtworkSource));
    public string ArtworkTarget => Text(nameof(ArtworkTarget));
    public string ConversionModeTitle => Text(nameof(ConversionModeTitle));
    public string ConversionModeNew => Text(nameof(ConversionModeNew));
    public string ConversionModeRepair => Text(nameof(ConversionModeRepair));
    public string ConversionModeNewDescription => Text(nameof(ConversionModeNewDescription));
    public string ConversionModeRepairDescription => Text(nameof(ConversionModeRepairDescription));
    public string RepairVersionTitle => Text(nameof(RepairVersionTitle));
    public string RepairVersionAutomatic => Text(nameof(RepairVersionAutomatic));
    public string RepairVersionHint => Text(nameof(RepairVersionHint));
    public string RepairVersionRequired => Text(nameof(RepairVersionRequired));
    public string CoreSectionTitle => Text(nameof(CoreSectionTitle));
    public string CoreSectionDescription => Text(nameof(CoreSectionDescription));
    public string SaveSlot => Text(nameof(SaveSlot));
    public string SaveSlotHint => Text(nameof(SaveSlotHint));
    public string SourceSlot => Text(nameof(SourceSlot));
    public string SourceSlotHint => Text(nameof(SourceSlotHint));
    public string TargetSlot => Text(nameof(TargetSlot));
    public string TargetSlotHint => Text(nameof(TargetSlotHint));
    public string ChooseFile => Text(nameof(ChooseFile));
    public string ChooseFolder => Text(nameof(ChooseFolder));
    public string CliPath => Text(nameof(CliPath));
    public string CliPathHint => Text(nameof(CliPathHint));
    public string Browse => Text(nameof(Browse));
    public string Inspect => Text(nameof(Inspect));
    public string InspectProgress => Text(nameof(InspectProgress));
    public string InspectEvents => Text(nameof(InspectEvents));
    public string DryRunTitle => Text(nameof(DryRunTitle));
    public string DryRunDescription => Text(nameof(DryRunDescription));
    public string RunDryRun => Text(nameof(RunDryRun));
    public string DryRunGate => Text(nameof(DryRunGate));
    public string WriteTitle => Text(nameof(WriteTitle));
    public string WriteDescription => Text(nameof(WriteDescription));
    public string WriteSelectedSave => Text(nameof(WriteSelectedSave));
    public string WriteUnavailable => Text(nameof(WriteUnavailable));
    public string TransactionDetails => Text(nameof(TransactionDetails));
    public string BackupAndManifest => Text(nameof(BackupAndManifest));
    public string OneTarget => Text(nameof(OneTarget));
    public string RollbackTitle => Text(nameof(RollbackTitle));
    public string RollbackDescription => Text(nameof(RollbackDescription));
    public string ManifestPath => Text(nameof(ManifestPath));
    public string RollbackFromManifest => Text(nameof(RollbackFromManifest));
    public string OptionalSectionTitle => Text(nameof(OptionalSectionTitle));
    public string OptionalSectionDescription => Text(nameof(OptionalSectionDescription));
    public string ExperimentalCec => Text(nameof(ExperimentalCec));
    public string ExperimentalCecHint => Text(nameof(ExperimentalCecHint));
    public string CecSourceDirectory => Text(nameof(CecSourceDirectory));
    public string CecTargetCache => Text(nameof(CecTargetCache));
    public string InspectCec => Text(nameof(InspectCec));
    public string RunCecDryRun => Text(nameof(RunCecDryRun));
    public string CecAcknowledge => Text(nameof(CecAcknowledge));
    public string WriteCec => Text(nameof(WriteCec));
    public string RollbackCec => Text(nameof(RollbackCec));
    public string ExtDataNotice => Text(nameof(ExtDataNotice));
    public string ExtDataInstallUnavailable => Text(nameof(ExtDataInstallUnavailable));
    public string ResultTitle => Text(nameof(ResultTitle));
    public string ResultEmpty => Text(nameof(ResultEmpty));
    public string OperationHistory => Text(nameof(OperationHistory));
    public string Ready => Text(nameof(Ready));
    public string Working => Text(nameof(Working));
    public string Failed => Text(nameof(Failed));
    public string Inspected => Text(nameof(Inspected));
    public string DryRunAuthorized => Text(nameof(DryRunAuthorized));
    public string Written => Text(nameof(Written));
    public string RolledBack => Text(nameof(RolledBack));
    public string ConfirmWriteTitle => Text(nameof(ConfirmWriteTitle));
    public string ConfirmWriteBody => Text(nameof(ConfirmWriteBody));
    public string ConfirmRollbackTitle => Text(nameof(ConfirmRollbackTitle));
    public string ConfirmRollbackBody => Text(nameof(ConfirmRollbackBody));
    public string ConfirmCecTitle => Text(nameof(ConfirmCecTitle));
    public string ConfirmCecBody => Text(nameof(ConfirmCecBody));
    public string Continue => Text(nameof(Continue));
    public string Cancel => Text(nameof(Cancel));
    public string OpenFolder => Text(nameof(OpenFolder));
    public string ExpectedCliMissing => Text(nameof(ExpectedCliMissing));
    public string InvalidCorePaths => Text(nameof(InvalidCorePaths));
    public string FileChangedAfterDryRun => Text(nameof(FileChangedAfterDryRun));
    public string CecDisabled => Text(nameof(CecDisabled));
    public string CecAcknowledgementRequired => Text(nameof(CecAcknowledgementRequired));
    public string CecPathsRequired => Text(nameof(CecPathsRequired));
    public string CecFingerprintMissing => Text(nameof(CecFingerprintMissing));
    public string SystemPathsRequired => Text(nameof(SystemPathsRequired));
    public string ExtrasPathsRequired => Text(nameof(ExtrasPathsRequired));
    public string ExtrasFingerprintMissing => Text(nameof(ExtrasFingerprintMissing));
    public string OptionalDataNeedsConfiguration => Text(nameof(OptionalDataNeedsConfiguration));
    public string SharedSystem => Text(nameof(SharedSystem));
    public string SystemSource => Text(nameof(SystemSource));
    public string SystemTarget => Text(nameof(SystemTarget));
    public string SystemMergeWarning => Text(nameof(SystemMergeWarning));
    public string RunSystemDryRun => Text(nameof(RunSystemDryRun));
    public string WriteSystem => Text(nameof(WriteSystem));
    public string SystemManifest => Text(nameof(SystemManifest));
    public string OptionalExtData => Text(nameof(OptionalExtData));
    public string GuildCards => Text(nameof(GuildCards));
    public string Quests => Text(nameof(Quests));
    public string ExtDataSource => Text(nameof(ExtDataSource));
    public string ExtDataSourceHint => Text(nameof(ExtDataSourceHint));
    public string StagingDirectory => Text(nameof(StagingDirectory));
    public string ExtDataTarget => Text(nameof(ExtDataTarget));
    public string PreviewStaging => Text(nameof(PreviewStaging));
    public string WriteStaging => Text(nameof(WriteStaging));
    public string PreviewInstall => Text(nameof(PreviewInstall));
    public string InstallExtData => Text(nameof(InstallExtData));
    public string ExtDataManifest => Text(nameof(ExtDataManifest));
    public string CecSourceDirectoryHint => Text(nameof(CecSourceDirectoryHint));
    public string CecTargetCacheHint => Text(nameof(CecTargetCacheHint));

    public string DescribeResolvedSource(string path) => string.Format(Text("ResolvedSource"), path);
    public string DescribeResolvedTarget(string path) => string.Format(Text("ResolvedTarget"), path);
    public string DescribeResolvedExtData(string path) => string.Format(Text("ResolvedExtData"), path);
    public string DescribeRepairVersionAmbiguous(string candidates) =>
        string.Format(Text("RepairVersionAmbiguous"), candidates);
    public string DescribeRepairVersionDetected(string candidates) =>
        string.Format(Text("RepairVersionDetected"), candidates);
    public string DescribePathError(SavePathResolutionError error) => Text($"PathError_{error}");

    private string Text(string key)
    {
        var table = _language == AppLanguageOverride.Chinese ? Chinese : English;
        return table.TryGetValue(key, out var value) ? value : English[key];
    }

    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        [nameof(AppTitle)] = "MH3G Save Converter",
        [nameof(AppSubtitle)] = "Japanese MH3G 3DS to Wii U / Cemu",
        [nameof(Language)] = "Language",
        [nameof(LanguageSystem)] = "System default",
        [nameof(LanguageChinese)] = "Simplified Chinese",
        [nameof(LanguageEnglish)] = "English",
        [nameof(AboutUpdates)] = "About & Updates",
        [nameof(AboutDescription)] = "MH3G Save Converter uses the bundled local Rust converter. Update checks read only the official MHToolkit GitHub Release metadata.",
        [nameof(CurrentVersion)] = "Current version",
        [nameof(CheckForUpdates)] = "Check for Updates",
        [nameof(CheckingForUpdates)] = "Contacting GitHub…",
        [nameof(UpdateAvailableTitle)] = "Update Available",
        [nameof(UpdateAvailableSummary)] = "Current {0} · Latest {1}",
        [nameof(ReleaseNotes)] = "Release notes",
        [nameof(NoReleaseNotes)] = "No release notes were provided for this version.",
        [nameof(OpenReleasePage)] = "Open Release Page",
        [nameof(UpToDateTitle)] = "Up to date",
        [nameof(UpToDateMessage)] = "Version {0} is the latest published release.",
        [nameof(UpdateCheckFailed)] = "Unable to check for updates",
        [nameof(UpdateNetworkNote)] = "The first launch each day checks GitHub Releases once. A blocked or unavailable network never blocks or changes local save operations; use this button to retry manually.",
        [nameof(Close)] = "Close",
        [nameof(StageInput)] = "Input",
        [nameof(StageInspect)] = "Inspect",
        [nameof(StageDryRun)] = "Dry Run",
        [nameof(StageWrite)] = "Write / Rollback",
        [nameof(NextStep)] = "Next step",
        [nameof(NextAfterInspect)] = "Core inputs are verified. Configure optional system or ExtData next; if you do not need either, leave them off and then continue to the core Dry Run.",
        [nameof(NextAfterDryRun)] = "Core Dry Run succeeded. Review the report, then choose Confirm and write core save. A final confirmation dialog will appear before any write.",
        [nameof(NextAfterWrite)] = "Core save was written with transaction evidence. Review the report and manifest below; optional data remains a separate, explicit workflow.",
        [nameof(NextAfterCoreWriteWithOptionalData)] = "Core save was written. Finish the selected optional system or ExtData transaction next; each has its own Dry Run and confirmation.",
        [nameof(NextAfterOptional)] = "An optional-data step completed. Continue with the next enabled optional action; the core flow keeps its own Dry Run and write authorization.",
        [nameof(NextAfterRollback)] = "Rollback completed. Inspect the source and target again before starting another migration.",
        [nameof(GoToDryRun)] = "Run core Dry Run",
        [nameof(GoToCoreDryRun)] = "Continue to core Dry Run",
        [nameof(ConfigureOptionalData)] = "Configure optional data",
        [nameof(ContinueOptionalData)] = "Continue optional data",
        [nameof(ConfirmAndWrite)] = "Confirm and write core save",
        [nameof(ReturnToCoreFlow)] = "Return to core workflow",
        [nameof(ReviewTransaction)] = "Review report and manifest",
        [nameof(HeroTitle)] = "A local, transaction-backed migration",
        [nameof(HeroDescription)] = "Select one slot, then choose a file or its direct folder. Inspect first, preview with a read-only Dry Run, then authorize one resolved target.",
        [nameof(HeroSafety)] = "No archive discovery. No cloud upload. No recursive MLC overwrite.",
        [nameof(ArtworkSource)] = "Source file or folder",
        [nameof(ArtworkTarget)] = "One resolved target",
        [nameof(ConversionModeTitle)] = "Conversion mode",
        [nameof(ConversionModeNew)] = "New conversion",
        [nameof(ConversionModeRepair)] = "Repair an already converted save",
        [nameof(ConversionModeNewDescription)] = "Create a Wii U / Cemu slot from an original Japanese 3DS user# file.",
        [nameof(ConversionModeRepairDescription)] = "Already converted? Add the original 3DS user# and the latest matching Wii U / Cemu user# that you have continued playing. The repair keeps later Wii U progress and only updates fields that still match a supported older converter. To repair received guild cards and offline partners too, enable Guild cards below and select the original 3DS ExtData user directory.",
        [nameof(RepairVersionTitle)] = "Original converter version",
        [nameof(RepairVersionAutomatic)] = "Detect automatically",
        [nameof(RepairVersionHint)] = "Keep automatic detection unless Dry Run reports multiple incompatible candidates. Choosing a version invalidates the previous preview and requires another Dry Run.",
        [nameof(RepairVersionRequired)] = "Choose one detected converter version and run Dry Run again",
        ["RepairVersionAmbiguous"] = "Dry Run found incompatible candidates: {0}. Select the version used originally, then run Dry Run again.",
        ["RepairVersionDetected"] = "Detection is safe to apply automatically. Matching revision range: {0}.",
        [nameof(CoreSectionTitle)] = "Core slot",
        [nameof(CoreSectionDescription)] = "Choose one user# slot. A source folder resolves only its direct child; an output folder resolves to that same user# name.",
        [nameof(SaveSlot)] = "Save slot",
        [nameof(SaveSlotHint)] = "This selects the direct user# child used when you choose a folder. A directly selected source file must match it.",
        [nameof(SourceSlot)] = "3DS source",
        [nameof(SourceSlotHint)] = "Choose user1, user2, or user3, or a folder that directly contains the selected file. No archive or recursive SD-card search is used.",
        [nameof(TargetSlot)] = "Cemu target or export folder",
        [nameof(TargetSlotHint)] = "Choose a matching existing Cemu user# file, or an output folder. A folder becomes <folder>/<selected user#>; nothing is created until Write.",
        [nameof(ChooseFile)] = "File…",
        [nameof(ChooseFolder)] = "Folder…",
        [nameof(CliPath)] = "Converter CLI",
        [nameof(CliPathHint)] = "Packaging places mh3g-save-convert.exe beside the app. You may choose an explicit signed sidecar for development.",
        [nameof(Browse)] = "Browse",
        [nameof(Inspect)] = "Inspect files",
        [nameof(InspectProgress)] = "Inspect progress",
        [nameof(InspectEvents)] = "Inspect events",
        [nameof(DryRunTitle)] = "Preview before any write",
        [nameof(DryRunDescription)] = "Dry Run previews the resolved source and target without writing an output, backup, manifest, or CEC data.",
        [nameof(RunDryRun)] = "Run Dry Run",
        [nameof(DryRunGate)] = "A successful Dry Run binds this screen to the source SHA-256 and either the target SHA-256 or the target's required absence.",
        [nameof(WriteTitle)] = "Write one authorized target",
        [nameof(WriteDescription)] = "Before Write, the app rechecks the resolved source and target state. The transaction creates its own backup and manifest.",
        [nameof(WriteSelectedSave)] = "Write selected save",
        [nameof(WriteUnavailable)] = "Inspect both paths and complete a current Dry Run before writing.",
        [nameof(TransactionDetails)] = "Transaction scope",
        [nameof(BackupAndManifest)] = "Backup and manifest are created beside this one resolved target only.",
        [nameof(OneTarget)] = "1 resolved target",
        [nameof(RollbackTitle)] = "Rollback a known transaction",
        [nameof(RollbackDescription)] = "Rollback accepts only the exact manifest created by the converter. It never treats a directory as a rollback request.",
        [nameof(ManifestPath)] = "Transaction manifest",
        [nameof(RollbackFromManifest)] = "Rollback from manifest",
        [nameof(OptionalSectionTitle)] = "Optional data",
        [nameof(OptionalSectionDescription)] = "Shared system carries housekeeper gallery/movie unlocks; ExtData carries cards and quests. They are separate, explicit transactions. CEC stays isolated and disabled until you enable it.",
        [nameof(ExperimentalCec)] = "Experimental CEC",
        [nameof(ExperimentalCecHint)] = "CEC is a separate StreetPass / Hunter Search cache. Guild-card and offline-partner migration do not require it.",
        [nameof(CecSourceDirectory)] = "3DS CEC mailbox directory",
        [nameof(CecTargetCache)] = "Cemu cec cache",
        ["CecSourceDirectoryHint"] = "Choose the exact CEC/00048100 mailbox folder. It is separate from the ExtData user directory and is never searched recursively.",
        ["CecTargetCacheHint"] = "Choose the exact Cemu cec file, usually inside the selected Wii U save directory.",
        [nameof(InspectCec)] = "Inspect CEC",
        [nameof(RunCecDryRun)] = "Run CEC Dry Run",
        [nameof(CecAcknowledge)] = "I understand that CEC import remains experimental",
        [nameof(WriteCec)] = "Write experimental CEC",
        [nameof(RollbackCec)] = "Rollback CEC manifest",
        [nameof(ExtDataNotice)] = "ExtData is optional. Choose its exact user directory (or only its direct 00000481 parent). Staging always converts the complete eight-file set; the group checkboxes do not filter that output and select groups for the read-only target preview.",
        [nameof(ExtDataInstallUnavailable)] = "Windows installs complete ExtData groups through the Rust sidecar's recovery journal and ReplaceFileW-backed transaction. The emulator must remain closed.",
        [nameof(ResultTitle)] = "Structured report",
        [nameof(ResultEmpty)] = "Run an inspection or Dry Run to see the CLI JSON report here.",
        [nameof(OperationHistory)] = "This session",
        [nameof(Ready)] = "Ready",
        [nameof(Working)] = "Working",
        [nameof(Failed)] = "Operation failed",
        [nameof(Inspected)] = "Inputs inspected",
        [nameof(DryRunAuthorized)] = "Dry Run authorized",
        [nameof(Written)] = "Written with transaction evidence",
        [nameof(RolledBack)] = "Rolled back from manifest",
        [nameof(ConfirmWriteTitle)] = "Write the selected Cemu save?",
        [nameof(ConfirmWriteBody)] = "This replaces exactly one selected target after a final SHA-256 check. The Rust CLI will create its transaction backup and manifest.",
        [nameof(ConfirmRollbackTitle)] = "Restore from this manifest?",
        [nameof(ConfirmRollbackBody)] = "Rollback restores only the target bound to this converter-created manifest.",
        [nameof(ConfirmCecTitle)] = "Write experimental CEC data?",
        [nameof(ConfirmCecBody)] = "This writes only the selected Cemu cec cache after a separate CEC Dry Run. It does not alter user#, card#, or quest# files.",
        [nameof(Continue)] = "Continue",
        [nameof(Cancel)] = "Cancel",
        [nameof(OpenFolder)] = "Open folder",
        [nameof(ExpectedCliMissing)] = "The bundled converter CLI is missing. Choose the signed mh3g-save-convert.exe sidecar before running a command.",
        [nameof(InvalidCorePaths)] = "Choose a valid user1, user2, or user3 source and a matching target file or export folder.",
        [nameof(FileChangedAfterDryRun)] = "The source or target state changed after Dry Run. Inspect and run Dry Run again before writing.",
        [nameof(CecDisabled)] = "Enable Experimental CEC to use its isolated commands.",
        [nameof(CecAcknowledgementRequired)] = "Acknowledge the experimental CEC warning before its write command is available.",
        [nameof(CecPathsRequired)] = "Choose the exact CEC mailbox directory and Cemu cec target path.",
        [nameof(CecFingerprintMissing)] = "CEC Dry Run did not provide the aggregate record-set and target JSON fingerprints.",
        [nameof(SystemPathsRequired)] = "Choose the exact 3DS source system and an existing initialized Cemu system before running this separate merge.",
        [nameof(ExtrasPathsRequired)] = "Choose at least one ExtData group plus explicit source and staging directories.",
        [nameof(ExtrasFingerprintMissing)] = "The ExtData Dry Run did not provide the expected component or set fingerprints.",
        [nameof(OptionalDataNeedsConfiguration)] = "Finish configuring the selected system or ExtData paths before the core Dry Run.",
        [nameof(SharedSystem)] = "Shared system",
        [nameof(SystemSource)] = "3DS system file",
        [nameof(SystemTarget)] = "Existing initialized Cemu system file",
        [nameof(SystemMergeWarning)] = "System is shared by all three character slots and may contain settings or data for the other slots. Supply both the 3DS source and the existing Cemu target. The converter merges only housekeeper gallery/movie flags and preserves every other Cemu byte.",
        [nameof(RunSystemDryRun)] = "Run system Dry Run",
        [nameof(WriteSystem)] = "Merge gallery/movie flags",
        [nameof(SystemManifest)] = "System manifest",
        [nameof(OptionalExtData)] = "Optional ExtData",
        [nameof(GuildCards)] = "Guild cards & offline partners",
        [nameof(Quests)] = "Quests",
        [nameof(ExtDataSource)] = "3DS ExtData user directory",
        ["ExtDataSourceHint"] = "Choose .../extdata/00000000/00000481/user, or only its direct 00000481 parent. Do not choose an SDMC or MLC root.",
        [nameof(StagingDirectory)] = "Staging directory",
        [nameof(ExtDataTarget)] = "Cemu ExtData target directory",
        [nameof(PreviewStaging)] = "Preview complete staging conversion",
        [nameof(WriteStaging)] = "Write complete staging conversion",
        [nameof(PreviewInstall)] = "Preview selected groups",
        [nameof(InstallExtData)] = "Install selected ExtData",
        [nameof(ExtDataManifest)] = "ExtData recovery manifest",
        ["ResolvedSource"] = "Resolved source: {0}",
        ["ResolvedTarget"] = "Output will be: {0}",
        ["ResolvedExtData"] = "Resolved ExtData user directory: {0}",
        ["PathError_MissingSourceSelection"] = "Choose a 3DS source file or folder first.",
        ["PathError_MissingTargetSelection"] = "Choose a Cemu target file or export folder first.",
        ["PathError_InvalidSlot"] = "Choose user1, user2, or user3.",
        ["PathError_SourcePathMissing"] = "The selected 3DS source file is no longer available.",
        ["PathError_SourceSlotMissing"] = "The selected source folder does not directly contain the selected user# file.",
        ["PathError_SourceSlotNameMismatch"] = "The selected source file does not match the selected user# slot.",
        ["PathError_TargetPathMissing"] = "Choose an existing Cemu user# file or an existing export folder.",
        ["PathError_TargetSlotNameMismatch"] = "The selected Cemu target file does not match the selected user# slot.",
        ["PathError_ExtDataPathMissing"] = "The selected ExtData location is not an available directory.",
        ["PathError_ExtDataUserDirectoryMissing"] = "The selected ExtData parent does not directly contain a user directory.",
        ["PathError_InvalidPath"] = "The selected path is invalid.",
    };

    private static readonly IReadOnlyDictionary<string, string> Chinese = new Dictionary<string, string>
    {
        [nameof(AppTitle)] = "MH3G 存档转换器",
        [nameof(AppSubtitle)] = "日版 MH3G 3DS 到 Wii U / Cemu",
        [nameof(Language)] = "语言",
        [nameof(LanguageSystem)] = "跟随系统",
        [nameof(LanguageChinese)] = "简体中文",
        [nameof(LanguageEnglish)] = "English",
        [nameof(AboutUpdates)] = "关于与更新",
        [nameof(AboutDescription)] = "MH3G Save Converter 使用内置的本地 Rust 转换器。更新检查只读取 MHToolkit 官方 GitHub Release 元数据。",
        [nameof(CurrentVersion)] = "当前版本",
        [nameof(CheckForUpdates)] = "检查更新",
        [nameof(CheckingForUpdates)] = "正在连接 GitHub…",
        [nameof(UpdateAvailableTitle)] = "发现新版本",
        [nameof(UpdateAvailableSummary)] = "当前 {0} · 最新 {1}",
        [nameof(ReleaseNotes)] = "更新说明",
        [nameof(NoReleaseNotes)] = "该版本未提供更新说明。",
        [nameof(OpenReleasePage)] = "打开发布页面",
        [nameof(UpToDateTitle)] = "已经是最新版",
        [nameof(UpToDateMessage)] = "版本 {0} 是当前最新正式版。",
        [nameof(UpdateCheckFailed)] = "无法检查更新",
        [nameof(UpdateNetworkNote)] = "每天首次启动会检查一次 GitHub Release；网络受限或不可用时不会阻塞或改动任何本地存档，也可以在这里手动重试。",
        [nameof(Close)] = "关闭",
        [nameof(StageInput)] = "输入",
        [nameof(StageInspect)] = "检查",
        [nameof(StageDryRun)] = "Dry Run",
        [nameof(StageWrite)] = "写入 / 回滚",
        [nameof(NextStep)] = "下一步",
        [nameof(NextAfterInspect)] = "核心输入已验证。请先配置可选 system 或 ExtData；不需要时保持关闭，然后继续核心 Dry Run。",
        [nameof(NextAfterDryRun)] = "核心 Dry Run 已成功。请先查看报告，再选择“确认并写入核心存档”；真正写入前仍会出现最终确认对话框。",
        [nameof(NextAfterWrite)] = "核心存档已携带事务证据写入。请查看下方报告和 manifest；可选数据仍是独立、明确的流程。",
        [nameof(NextAfterCoreWriteWithOptionalData)] = "核心存档已写入。请继续完成已选择的 system 或 ExtData；每项都有独立的 Dry Run 和确认步骤。",
        [nameof(NextAfterOptional)] = "一个可选数据步骤已完成。请继续执行下一个已启用的可选操作；核心流程仍保留独立的 Dry Run 和写入授权。",
        [nameof(NextAfterRollback)] = "回滚已完成。开始新的迁移前，请重新检查源文件和目标。",
        [nameof(GoToDryRun)] = "运行核心 Dry Run",
        [nameof(GoToCoreDryRun)] = "继续核心 Dry Run",
        [nameof(ConfigureOptionalData)] = "配置可选数据",
        [nameof(ContinueOptionalData)] = "继续可选数据",
        [nameof(ConfirmAndWrite)] = "确认并写入核心存档",
        [nameof(ReturnToCoreFlow)] = "回到核心流程",
        [nameof(ReviewTransaction)] = "查看报告和 manifest",
        [nameof(HeroTitle)] = "本地、事务保护的存档迁移",
        [nameof(HeroDescription)] = "先选择一个槽位，再选择文件或其直接父目录。先检查，再只读 Dry Run，最后只授权一个解析后的目标。",
        [nameof(HeroSafety)] = "不扫描压缩包，不上传云端，不递归覆盖 MLC。",
        [nameof(ArtworkSource)] = "源文件或目录",
        [nameof(ArtworkTarget)] = "一个解析后的目标",
        [nameof(ConversionModeTitle)] = "转换模式",
        [nameof(ConversionModeNew)] = "全新转换",
        [nameof(ConversionModeRepair)] = "修复已转换存档",
        [nameof(ConversionModeNewDescription)] = "使用原始日版 3DS user# 创建新的 Wii U / Cemu 角色存档。",
        [nameof(ConversionModeRepairDescription)] = "已经转换过？请同时添加原始 3DS user#，以及继续游玩后的最新同槽位 Wii U / Cemu user#。修复流程会保留后续 Wii U 进度，只更新仍与受支持旧版转换器结果一致的字段。还要修复收到的公会名片和离线伙伴时，请在下方启用“公会名片与离线伙伴”，并选择原始 3DS ExtData user 目录。",
        [nameof(RepairVersionTitle)] = "原转换器版本",
        [nameof(RepairVersionAutomatic)] = "自动检测",
        [nameof(RepairVersionHint)] = "默认保持自动检测。只有 Dry Run 报告多个互不兼容的候选版本时才需要手动选择；选择后旧预览会失效，必须重新 Dry Run。",
        [nameof(RepairVersionRequired)] = "请选择一个检测到的转换器版本，然后重新运行 Dry Run",
        ["RepairVersionAmbiguous"] = "Dry Run 检测到互不兼容的候选版本：{0}。请选择当时使用的版本，然后重新运行 Dry Run。",
        ["RepairVersionDetected"] = "当前检测结果可以安全自动应用。匹配的版本范围：{0}。",
        [nameof(CoreSectionTitle)] = "核心角色槽位",
        [nameof(CoreSectionDescription)] = "选择一个 user# 槽位。源目录只解析它的直接子文件；输出目录会解析为同名 user#。",
        [nameof(SaveSlot)] = "存档槽位",
        [nameof(SaveSlotHint)] = "选择目录时会使用这个直接子文件。直接选择的源文件必须与这个槽位同名。",
        [nameof(SourceSlot)] = "3DS 源存档",
        [nameof(SourceSlotHint)] = "选择 user1、user2 或 user3，或直接包含所选文件的目录。不扫描压缩包，也不会递归扫描 SD 卡。",
        [nameof(TargetSlot)] = "Cemu 目标或导出目录",
        [nameof(TargetSlotHint)] = "选择同名且已初始化的 Cemu user# 文件，或输出目录。目录会解析为 <目录>/<所选 user#>；只有写入时才会创建文件。",
        [nameof(ChooseFile)] = "文件…",
        [nameof(ChooseFolder)] = "文件夹…",
        [nameof(CliPath)] = "转换器 CLI",
        [nameof(CliPathHint)] = "打包时会把 mh3g-save-convert.exe 放在应用旁。开发时可明确选择已签名的 sidecar。",
        [nameof(Browse)] = "选择",
        [nameof(Inspect)] = "检查文件",
        [nameof(InspectProgress)] = "检查任务进度",
        [nameof(InspectEvents)] = "检查事件标记",
        [nameof(DryRunTitle)] = "任何写入之前先预览",
        [nameof(DryRunDescription)] = "Dry Run 会预览解析后的源和目标，不会写入输出、备份、manifest 或 CEC 数据。",
        [nameof(RunDryRun)] = "运行 Dry Run",
        [nameof(DryRunGate)] = "成功的 Dry Run 会绑定源文件 SHA-256，以及目标 SHA-256 或目标必须保持不存在的状态。",
        [nameof(WriteTitle)] = "写入一个已授权目标",
        [nameof(WriteDescription)] = "写入前应用会重新检查解析后的源文件和目标状态。事务会自行创建备份和 manifest。",
        [nameof(WriteSelectedSave)] = "写入所选存档",
        [nameof(WriteUnavailable)] = "请先检查两个路径并完成当前有效的 Dry Run。",
        [nameof(TransactionDetails)] = "事务范围",
        [nameof(BackupAndManifest)] = "备份和 manifest 只会创建在这个解析后的目标文件旁。",
        [nameof(OneTarget)] = "1 个解析后的目标",
        [nameof(RollbackTitle)] = "回滚已知事务",
        [nameof(RollbackDescription)] = "回滚只接受转换器生成的准确 manifest，不会把文件夹当成回滚请求。",
        [nameof(ManifestPath)] = "事务 manifest",
        [nameof(RollbackFromManifest)] = "从 manifest 回滚",
        [nameof(OptionalSectionTitle)] = "可选数据",
        [nameof(OptionalSectionDescription)] = "共享 system 包含管家画廊/动画解锁记录，ExtData 包含名片与任务；两者都是独立、明确的事务。CEC 完全隔离，默认关闭。",
        [nameof(ExperimentalCec)] = "实验性 CEC",
        [nameof(ExperimentalCecHint)] = "CEC 是独立的擦身通信 / 猎人搜索缓存。公会名片和离线伙伴迁移不依赖它。",
        [nameof(CecSourceDirectory)] = "3DS CEC 邮箱目录",
        [nameof(CecTargetCache)] = "Cemu cec 缓存",
        ["CecSourceDirectoryHint"] = "请选择准确的 CEC/00048100 邮箱目录。它与 ExtData user 目录独立，应用不会递归搜索。",
        ["CecTargetCacheHint"] = "请选择准确的 Cemu cec 文件，通常位于所选 Wii U 存档目录中。",
        [nameof(InspectCec)] = "检查 CEC",
        [nameof(RunCecDryRun)] = "运行 CEC Dry Run",
        [nameof(CecAcknowledge)] = "我了解 CEC 导入仍是实验性功能",
        [nameof(WriteCec)] = "写入实验性 CEC",
        [nameof(RollbackCec)] = "回滚 CEC manifest",
        [nameof(ExtDataNotice)] = "ExtData 是可选项。请选择准确的 user 目录（或它的直接 00000481 父目录）。暂存转换始终生成完整八个文件；组复选框不会筛选这些输出，只决定只读目标预览的组件组。",
        [nameof(ExtDataInstallUnavailable)] = "Windows 会通过 Rust sidecar 的恢复日志和 ReplaceFileW 事务安装完整 ExtData 组件组；整个过程必须保持模拟器关闭。",
        [nameof(ResultTitle)] = "结构化报告",
        [nameof(ResultEmpty)] = "运行检查或 Dry Run 后，会在这里显示 CLI JSON 报告。",
        [nameof(OperationHistory)] = "本次会话",
        [nameof(Ready)] = "已就绪",
        [nameof(Working)] = "正在执行",
        [nameof(Failed)] = "操作失败",
        [nameof(Inspected)] = "输入已检查",
        [nameof(DryRunAuthorized)] = "Dry Run 已授权",
        [nameof(Written)] = "已写入事务证据",
        [nameof(RolledBack)] = "已从 manifest 回滚",
        [nameof(ConfirmWriteTitle)] = "写入所选 Cemu 存档？",
        [nameof(ConfirmWriteBody)] = "最终 SHA-256 检查后只会替换一个目标。Rust CLI 会创建事务备份和 manifest。",
        [nameof(ConfirmRollbackTitle)] = "从这个 manifest 恢复？",
        [nameof(ConfirmRollbackBody)] = "回滚只会恢复此转换器 manifest 绑定的目标。",
        [nameof(ConfirmCecTitle)] = "写入实验性 CEC 数据？",
        [nameof(ConfirmCecBody)] = "独立 CEC Dry Run 后只会写入所选 Cemu cec 缓存，不会修改 user#、card# 或 quest# 文件。",
        [nameof(Continue)] = "继续",
        [nameof(Cancel)] = "取消",
        [nameof(OpenFolder)] = "打开文件夹",
        [nameof(ExpectedCliMissing)] = "未找到打包的转换器 CLI。运行命令前请选择已签名的 mh3g-save-convert.exe sidecar。",
        [nameof(InvalidCorePaths)] = "请选择有效的 user1、user2 或 user3 源文件，以及同名的目标文件或导出目录。",
        [nameof(FileChangedAfterDryRun)] = "Dry Run 后源文件或目标状态发生变化。写入前请重新检查并运行 Dry Run。",
        [nameof(CecDisabled)] = "启用实验性 CEC 后才能使用它的独立命令。",
        [nameof(CecAcknowledgementRequired)] = "使用 CEC 写入命令前请确认实验性警告。",
        [nameof(CecPathsRequired)] = "请选择准确的 CEC 邮箱目录和 Cemu cec 目标路径。",
        [nameof(CecFingerprintMissing)] = "CEC Dry Run 没有提供聚合记录集和目标 JSON 指纹。",
        [nameof(SystemPathsRequired)] = "运行这个独立合并前，请选择准确的 3DS 源 system 和已存在、已初始化的 Cemu system。",
        [nameof(ExtrasPathsRequired)] = "请至少选择一个 ExtData 组，以及准确的源目录和临时目录。",
        [nameof(ExtrasFingerprintMissing)] = "ExtData Dry Run 没有提供预期的组件或集合指纹。",
        [nameof(OptionalDataNeedsConfiguration)] = "请先完成已选择的 system 或 ExtData 路径配置，再运行核心 Dry Run。",
        [nameof(SharedSystem)] = "共享 system",
        [nameof(SystemSource)] = "3DS system 文件",
        [nameof(SystemTarget)] = "已存在且已初始化的 Cemu system 文件",
        [nameof(SystemMergeWarning)] = "system 由三个角色槽位共享，可能同时保存其他槽位数据或设置。必须同时提供 3DS 源 system 和现有 Cemu 目标 system；转换器只合并管家画廊/动画标记，其他 Cemu 字节全部保持不变。",
        [nameof(RunSystemDryRun)] = "运行 system Dry Run",
        [nameof(WriteSystem)] = "合并画廊/动画标记",
        [nameof(SystemManifest)] = "system manifest",
        [nameof(OptionalExtData)] = "可选 ExtData",
        [nameof(GuildCards)] = "公会名片与离线伙伴",
        [nameof(Quests)] = "任务",
        [nameof(ExtDataSource)] = "3DS ExtData user 目录",
        ["ExtDataSourceHint"] = "请选择 .../extdata/00000000/00000481/user，或它的直接 00000481 父目录。不要选择 SDMC 或 MLC 根目录。",
        [nameof(StagingDirectory)] = "临时转换目录",
        [nameof(ExtDataTarget)] = "Cemu ExtData 目标目录",
        [nameof(PreviewStaging)] = "预览完整临时转换",
        [nameof(WriteStaging)] = "写入完整临时转换",
        [nameof(PreviewInstall)] = "预览所选组件组",
        [nameof(InstallExtData)] = "安装所选 ExtData",
        [nameof(ExtDataManifest)] = "ExtData 恢复 manifest",
        ["ResolvedSource"] = "解析后的源文件：{0}",
        ["ResolvedTarget"] = "最终输出位置：{0}",
        ["ResolvedExtData"] = "解析后的 ExtData user 目录：{0}",
        ["PathError_MissingSourceSelection"] = "请先选择 3DS 源文件或目录。",
        ["PathError_MissingTargetSelection"] = "请先选择 Cemu 目标文件或导出目录。",
        ["PathError_InvalidSlot"] = "请选择 user1、user2 或 user3。",
        ["PathError_SourcePathMissing"] = "所选 3DS 源文件已经不可用。",
        ["PathError_SourceSlotMissing"] = "所选源目录不直接包含当前选择的 user# 文件。",
        ["PathError_SourceSlotNameMismatch"] = "所选源文件与当前选择的 user# 槽位不匹配。",
        ["PathError_TargetPathMissing"] = "请选择已存在的 Cemu user# 文件或已存在的导出目录。",
        ["PathError_TargetSlotNameMismatch"] = "所选 Cemu 目标文件与当前选择的 user# 槽位不匹配。",
        ["PathError_ExtDataPathMissing"] = "所选 ExtData 位置不是可用目录。",
        ["PathError_ExtDataUserDirectoryMissing"] = "所选 ExtData 父目录不直接包含 user 目录。",
        ["PathError_InvalidPath"] = "所选路径无效。",
    };
}
